// OZ Browser — Cookies I/O en 4 formatos (1.7c).
//
// Qué hace: encode/decode de jars de cookies en 4 formatos compatibles para
// que un usuario pueda migrar entre OZ ↔ AdsPower ↔ Multilogin ↔ curl/wget.
//
// Formatos soportados:
//   1. 'oz'        — JSON nativo OZ (round-trip lossless con session.cookies.get())
//   2. 'netscape'  — texto plano cookies.txt (estándar curl/wget/Firefox)
//   3. 'adspower' — JSON AdsPower-compat (devtools-style con storeId)
//   4. 'multilogin' — JSON Multilogin-compat (devtools-style sin storeId)
//
// Doc: docs/modules/cookies-io.md
// ADR: docs/architecture/0016-tab-context-menu.md (sección Cookies I/O)
//
// Modelo "canónico" interno (lo que devuelve session.cookies.get() en
// Electron 42; ver https://www.electronjs.org/docs/latest/api/structures/cookie):
//   {
//     name, value, domain, hostOnly, path, secure, httpOnly,
//     session, expirationDate?, sameSite
//   }
//
// El encode toma un array canónico y devuelve string/file content.
// El decode toma string y devuelve array canónico.
//
// IMPORTANTE: este módulo NO toca Electron — los handlers en cookies-handlers.js
// hacen el bridge a session.cookies.{get,set}. Esto permite testear formatos
// 100% sync sin GUI.

const SUPPORTED_FORMATS = ['oz', 'netscape', 'adspower', 'multilogin']

class CookiesFormatError extends Error {
  constructor(format, message) {
    super(`cookies-io ${format}: ${message}`)
    this.code = 'COOKIES_FORMAT_ERROR'
    this.format = format
  }
}

// ======================== ENCODE ============================================

function encode(format, cookies) {
  if (!SUPPORTED_FORMATS.includes(format)) {
    throw new CookiesFormatError(
      format,
      `unsupported (use one of: ${SUPPORTED_FORMATS.join(', ')})`,
    )
  }
  switch (format) {
    case 'oz':
      return encodeOz(cookies)
    case 'netscape':
      return encodeNetscape(cookies)
    case 'adspower':
      return encodeAdsPower(cookies)
    case 'multilogin':
      return encodeMultilogin(cookies)
    default:
      throw new CookiesFormatError(format, 'unreachable')
  }
}

function encodeOz(cookies) {
  // Lossless: serialize the canonical record verbatim.
  const out = (cookies || []).map(toCanonical)
  return JSON.stringify(
    { format: 'oz', version: 1, exportedAt: Date.now(), cookies: out },
    null,
    2,
  )
}

function encodeNetscape(cookies) {
  // Format spec:
  //   domain  TAB flag TAB path TAB secure TAB expiration TAB name TAB value
  // flag = TRUE if domain starts with '.' (subdomains allowed), else FALSE.
  // secure = TRUE/FALSE
  // expiration = Unix epoch seconds, 0 for session cookies.
  const lines = ['# Netscape HTTP Cookie File', '# Generated by OZ Browser', '']
  for (const c of cookies || []) {
    const can = toCanonical(c)
    const domain = can.domain || ''
    const includesSubdomain = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const path = can.path || '/'
    const secure = can.secure ? 'TRUE' : 'FALSE'
    const expSec = can.expirationDate ? Math.floor(can.expirationDate) : 0 // session cookie
    const name = can.name || ''
    const value = can.value || ''
    // Names/values may not contain TAB or newline — defensive escape.
    const safe = (s) => String(s).replace(/[\t\r\n]/g, ' ')
    lines.push(
      [
        domain,
        includesSubdomain,
        path,
        secure,
        String(expSec),
        safe(name),
        safe(value),
      ].join('\t'),
    )
  }
  return lines.join('\n') + '\n'
}

function encodeAdsPower(cookies) {
  // AdsPower exports an array of cookie records using devtools shape with
  // storeId. We add storeId="0" (default profile in AdsPower).
  const out = (cookies || []).map((c) => {
    const can = toCanonical(c)
    return {
      name: can.name,
      value: can.value,
      domain: can.domain,
      path: can.path || '/',
      expirationDate: can.expirationDate,
      hostOnly: !!can.hostOnly,
      httpOnly: !!can.httpOnly,
      secure: !!can.secure,
      session: !!can.session || !can.expirationDate,
      sameSite: mapSameSiteToAdsPower(can.sameSite),
      storeId: '0',
    }
  })
  return JSON.stringify(out, null, 2)
}

function encodeMultilogin(cookies) {
  // Multilogin uses devtools shape WITHOUT storeId.
  const out = (cookies || []).map((c) => {
    const can = toCanonical(c)
    return {
      name: can.name,
      value: can.value,
      domain: can.domain,
      path: can.path || '/',
      expirationDate: can.expirationDate,
      hostOnly: !!can.hostOnly,
      httpOnly: !!can.httpOnly,
      secure: !!can.secure,
      session: !!can.session || !can.expirationDate,
      sameSite: mapSameSiteToMultilogin(can.sameSite),
    }
  })
  return JSON.stringify(out, null, 2)
}

// ======================== DECODE ============================================

function decode(format, content) {
  if (!SUPPORTED_FORMATS.includes(format)) {
    throw new CookiesFormatError(
      format,
      `unsupported (use one of: ${SUPPORTED_FORMATS.join(', ')})`,
    )
  }
  switch (format) {
    case 'oz':
      return decodeOz(content)
    case 'netscape':
      return decodeNetscape(content)
    case 'adspower':
      return decodeAdsPower(content)
    case 'multilogin':
      return decodeMultilogin(content)
    default:
      throw new CookiesFormatError(format, 'unreachable')
  }
}

function decodeOz(content) {
  let parsed
  try {
    parsed = JSON.parse(content)
  } catch (err) {
    throw new CookiesFormatError('oz', `invalid JSON: ${err.message}`)
  }
  // Tolerant: accept either {format,cookies:[]} or bare array.
  let arr
  if (Array.isArray(parsed)) arr = parsed
  else if (parsed && Array.isArray(parsed.cookies)) arr = parsed.cookies
  else throw new CookiesFormatError('oz', 'expected array or {cookies:[]}')
  return arr.map(toCanonical)
}

function decodeNetscape(content) {
  const out = []
  const lines = String(content).split(/\r?\n/)
  for (const raw of lines) {
    const line = raw.trim()
    if (!line) continue
    // Some Netscape exporters use "#HttpOnly_" prefix on lines for httpOnly
    // cookies (Curl convention). Recognize FIRST so we don't mistake it for a
    // plain comment line.
    let httpOnlyHint = false
    let working = line
    if (line.startsWith('#HttpOnly_')) {
      httpOnlyHint = true
      working = line.slice('#HttpOnly_'.length)
    } else if (line.startsWith('#')) {
      continue // regular comment
    }
    const parts = working.split('\t')
    if (parts.length < 7) continue // malformed — skip silently (resilient)
    const [domain, _flag, path, secure, expiration, name, ...valueParts] = parts
    const value = valueParts.join('\t') // value MAY contain tabs only after final field; defensive
    const expSec = parseInt(expiration, 10)
    out.push({
      name,
      value,
      domain,
      path: path || '/',
      secure: secure === 'TRUE',
      httpOnly: httpOnlyHint,
      hostOnly: !domain.startsWith('.'),
      session: !expSec || expSec === 0,
      expirationDate: expSec && expSec > 0 ? expSec : undefined,
      sameSite: 'no_restriction',
    })
  }
  return out
}

function decodeAdsPower(content) {
  let parsed
  try {
    parsed = JSON.parse(content)
  } catch (err) {
    throw new CookiesFormatError('adspower', `invalid JSON: ${err.message}`)
  }
  if (!Array.isArray(parsed)) {
    throw new CookiesFormatError('adspower', 'expected array')
  }
  return parsed.map((c) => ({
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path || '/',
    secure: !!c.secure,
    httpOnly: !!c.httpOnly,
    hostOnly: !!c.hostOnly,
    session: !!c.session,
    expirationDate: c.expirationDate,
    sameSite: mapSameSiteFromAdsPower(c.sameSite),
  }))
}

function decodeMultilogin(content) {
  let parsed
  try {
    parsed = JSON.parse(content)
  } catch (err) {
    throw new CookiesFormatError('multilogin', `invalid JSON: ${err.message}`)
  }
  if (!Array.isArray(parsed)) {
    throw new CookiesFormatError('multilogin', 'expected array')
  }
  return parsed.map((c) => ({
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path || '/',
    secure: !!c.secure,
    httpOnly: !!c.httpOnly,
    hostOnly: !!c.hostOnly,
    session: !!c.session,
    expirationDate: c.expirationDate,
    sameSite: mapSameSiteFromMultilogin(c.sameSite),
  }))
}

// ======================== HELPERS ===========================================

function toCanonical(c) {
  if (!c || typeof c !== 'object') return c
  return {
    name: c.name,
    value: c.value,
    domain: c.domain,
    path: c.path || '/',
    secure: !!c.secure,
    httpOnly: !!c.httpOnly,
    hostOnly:
      c.hostOnly !== undefined ? !!c.hostOnly : !c.domain || !c.domain.startsWith('.'),
    session: c.session !== undefined ? !!c.session : !c.expirationDate,
    expirationDate: c.expirationDate,
    sameSite: c.sameSite || 'no_restriction',
  }
}

// SameSite mapping helpers — Electron uses snake_case
// ('unspecified'|'no_restriction'|'lax'|'strict'), AdsPower/Multilogin use
// the same plus capitalized variants. We accept anything case-insensitive.
function normalizeSameSite(s) {
  if (!s) return 'no_restriction'
  const lower = String(s).toLowerCase()
  if (lower === 'no_restriction' || lower === 'none' || lower === 'no-restriction')
    return 'no_restriction'
  if (lower === 'lax') return 'lax'
  if (lower === 'strict') return 'strict'
  if (lower === 'unspecified') return 'unspecified'
  return 'no_restriction'
}
function mapSameSiteToAdsPower(s) {
  return normalizeSameSite(s)
}
function mapSameSiteToMultilogin(s) {
  return normalizeSameSite(s)
}
function mapSameSiteFromAdsPower(s) {
  return normalizeSameSite(s)
}
function mapSameSiteFromMultilogin(s) {
  return normalizeSameSite(s)
}

// ======================== EXPORTS ===========================================

module.exports = {
  encode,
  decode,
  SUPPORTED_FORMATS,
  CookiesFormatError,
  // Exposed for unit tests / direct callers:
  encodeOz,
  encodeNetscape,
  encodeAdsPower,
  encodeMultilogin,
  decodeOz,
  decodeNetscape,
  decodeAdsPower,
  decodeMultilogin,
  toCanonical,
  normalizeSameSite,
}
